project_id = "wotqxwqlmjcnrckfjgno"

[functions.send-application-confirmation]
verify_jwt = false

[functions.send-application-approval]
verify_jwt = false

[functions.send-password-setup]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.get-admin-applications]
verify_jwt = false

[functions.gmail-send-application-confirmation]
verify_jwt = false

[functions.gmail-send-application-approval]
verify_jwt = false

[functions.gmail-send-application-denial]
verify_jwt = false

[functions.gmail-send-password-setup]
verify_jwt = false

[functions.sync-tts-progress]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.update-application-status]
verify_jwt = false

[functions.resend-user-credentials]
verify_jwt = false

[functions.get-user-profile-for-admin]
verify_jwt = false

[functions.profile-login]
verify_jwt = false

[functions.revoke-application-access]
verify_jwt = false

[functions.change-admin-password]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = false

[functions.update-admin-profile]
verify_jwt = false

[functions.send-rsvp-confirmation]
verify_jwt = false

[functions.generate-ics-file]
verify_jwt = false

[functions.send-event-notifications]
verify_jwt = false

[functions.create-calendar-event]
verify_jwt = false

[functions.update-calendar-event]
verify_jwt = false

[functions.test-password]
verify_jwt = false

[functions.delete-calendar-event]
verify_jwt = false