-- Populate website_content table with current landing page content
INSERT INTO website_content (section_id, title, subtitle, content, metadata) VALUES
('hero', 'UC Investments Academy', 'Building the next generation of finance leaders', 'Connect UC undergraduate and graduate students with opportunities in the financial industry through free training, tools, and coaching.', '{"cta_primary": "Access Portal", "cta_secondary": "Explore the Program"}'),

('about', 'What is the UC Investments Academy?', '', 'Launched by UC Investments and UC Office of the President in 2022, this program prepares UC students for careers in finance and asset management. Initially starting with just 100 students at UC Merced, the program has expanded to multiple UC campuses and provides the one-stop UC destination for preparing for careers in finance.\n\nThe UC Investments Academy, which we created to connect UC undergrads with opportunities in the financial industry, has engaged 3000+ students across 9 UC campuses. The Academy provides free training, tools and coaching to all interested UC students.', '{}'),

('program', 'Our Complete Program', 'A comprehensive pathway designed to take you from awareness to career success in finance and asset management.', '<h3>AWARENESS</h3><p>Provide exposure to different areas of asset management<br>Clarify options for investment careers</p><h3>ACCESS</h3><p>Intentional approach to create a diverse and inclusive participant base</p><h3>EDUCATION</h3><p>Foundational personal finance concepts<br>Investment analysis and portfolio management education</p><h3>TRAINING</h3><p>Practical investment analysis and experience<br>''Soft skills'' for professional success</p><h3>NETWORK</h3><p>Provide exposure to investment professionals within and outside UC network<br>Create an investment and entrepreneurship community</p><h3>MENTORSHIP</h3><p>Mentors students can see as role models<br>Guidance on investing and career management</p><h3>CAREER</h3><p>Internships<br>Full-time job opportunities</p>', '{}'),

('benefits', 'Why Choose UC Investments Academy?', 'Everything you need to launch your finance career.', '<div class="grid grid-cols-1 md:grid-cols-2 gap-8"><div><h4>Real-World Experience</h4><p>Build financial literacy through comprehensive training and real-world investment experience.</p></div><div><h4>Free Training</h4><p>Free asset management training and professional development at no cost to students.</p></div><div><h4>Professional Network</h4><p>Connect with professionals across investments and wealth management industries.</p></div><div><h4>Mentorship Access</h4><p>Access mentorship and internship opportunities with industry leaders.</p></div></div><p>By the end of the program, participants are motivated and equipped with foundational knowledge to pursue a career in investments.</p>', '{}'),

('how-it-works', 'How the Program Works', 'The program consists of online classes and guest speakers from diverse backgrounds in the investment field.', '<h3>Investment Analysis Curriculum</h3><ul><li>Online self-study materials (20-30 hours per quarter)</li><li>2 live instructor-led Zoom training sessions (6 hours total)</li><li>Provided by Training The Street</li></ul><h3>Live Guest Speaker Sessions</h3><ul><li>2-3 Wednesday evening Zoom sessions per semester</li><li>Optional access to ~20 previously recorded sessions</li><li>Insider views into the investment arena</li></ul><h3>Virtual Work Experience</h3><ul><li>2+ virtual work assignments with investment firms</li><li>10-25 hours per semester</li><li>Provided by The Forage</li></ul><h3>Investment Community & Network</h3><ul><li>Interact with investors and like-minded UC students</li><li>Connect with firms recruiting Academy students</li><li>Access career opportunities</li></ul><h3>Financial Literacy Programming</h3><ul><li>Learn how to create wealth for your future</li><li>Personal financial literacy programming</li><li>1-2 hours of focused content</li></ul><h3>Career Strategy Sessions</h3><ul><li>Access to UC investments team members</li><li>Network of professionals for advice</li><li>Investment strategy guidance</li></ul>', '{}'),

('faq', 'Frequently Asked Questions', 'Everything you need to know about the UC Investments Academy.', '<h4>Who can apply to the UC Investments Academy?</h4><p>All UC undergraduate and graduate students are eligible to apply. We welcome students from all majors and academic backgrounds.</p><h4>Is there a cost to participate?</h4><p>No, the UC Investments Academy is completely free for all UC students. This includes all training materials, workshops, and certification opportunities.</p><h4>How much time commitment is required?</h4><p>The program requires approximately 20-30 hours per quarter for self-study materials, plus attendance at live sessions and virtual work experiences.</p><h4>What kind of career support is provided?</h4><p>We offer mentorship pairing, resume reviews, interview preparation, networking opportunities, and direct connections to recruiting firms.</p><h4>Can I participate if I have no finance background?</h4><p>Absolutely! The program is designed to take students from any starting point and provide foundational knowledge in finance and investments.</p>', '{}')

ON CONFLICT (section_id) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  content = EXCLUDED.content,
  metadata = EXCLUDED.metadata,
  updated_at = now();