// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wotqxwqlmjcnrckfjgno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvdHF4d3FsbWpjbnJja2ZqZ25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzE2NzAsImV4cCI6MjA3MTgwNzY3MH0.LB8FET8JRZ-1hxToBoQE-EoJ4Cri-xNqmFRZNRR2ke4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});